name: Go CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Build with Make
        run: make build

      - name: Test with Make
        run: make test

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag
        id: set-tag
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" || "${GITHUB_REF##*/}" == "master" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=test" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/netbox-checker:${{ env.TAG }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/netbox-checker:${{ env.TAG }}